version: "3.8"
services:
  data_collector:
    container_name: data_collector
    build: ./src/data_collection_service
    restart: always
    networks:
      - fas
    ports:
      - "10000:10000"
    volumes:
      - ./src/data_collection_service:/app
  data_manager:
    container_name: data_manager
    build: ./src/data_management_service
    restart: always
    networks:
      - fas
    ports:
      - "10001:10001"
    volumes:
      - ./src/data_management_service:/app
  data_miner:
    container_name: data_miner
    build: ./src/data_mining_service
    restart: always
    networks:
      - fas
    ports:
      - "10002:10002"
    volumes:
      - ./src/data_mining_service:/app
  monitor:
    container_name: monitor
    build: ./src/monitor_service
    restart: always
    networks:
      - fas
    ports:
      - "10003:10003"
    volumes:
      - ./src/monitor_service:/app
  reporter:
    container_name: reporter
    build: ./src/report_service
    restart: always
    networks:
      - fas
    ports:
      - "10004:10004"
    volumes:
      - ./src/report_service:/app
  trader:
    container_name: trader
    build: ./src/trading_service
    restart: always
    networks:
      - fas
    ports:
      - "10005:10005"
    volumes:
      - ./src/trading_service:/app
networks:
  fas:
